### ISSUE TITLE
Support for <mark> tag within markdown

### ISSUE THREAD

**Issue by enricoros** [widcardw/remark-mark-highlight#2]
Hi, just found and love this package. Works great, thanks for making it.

For my application, https://github.com/enricoros/big-agi, it would be semantically really useful if `<mark>sometext</mark>` tags within the text itself could be supported by this lib, in the same way `==sometext==` does. This is because == can appear within chats with greater frequency (AI generates code blocks and text blocks all intertwinded and can commonly be messy and produce false positives), while with `<mark>`, we can semantically make the app understand that the user meant to highlight.

Would it be possible to have an option to treat the `<mark>` tag like the highlight?
Thank you.

**Comment by widcardw** [comment]
The `<mark>` tag should be a native html tag, so is it possible to just add the css to enable the marker?

```css
mark { background-color: yellow }
```

**Comment by enricoros** [comment]
@widcardw thanks for the prompt answer. You're probably right, actually: I'm sure you're right and know much more than me. 

I've fully implemented the integration and the way I do it is: I have a `<mark/>` element (both AI or the user can use them) in the text, and before giving it to markdown I replace the `<mark>` with `==`. 
This way I keep the semantics of the text and then use this plugin for rendering.

You may consider it as an extra to support the `<mark>` element, so that people will have a single go-to plugin for their highlight needs.

**Comment by widcardw** [comment]
After searching some remark and rehype plugins, the [`rehype-raw`](https://github.com/rehypejs/rehype-raw) plugin may meet your need. It will parse the raw nodes again and recognize the embedded `<mark>` tag.

The `remark-mark-highlight` plugin is designed for editors like [Typora](https://github.com/typora) and [Obsidian](https://obsidian.md) so that the double equal sign syntax can be easily parsed as highlighted text, but the LLM may be pretrained as using embedded `<mark>` tag to highlight some text. As a result, using rehype-raw may be better.

**Comment by enricoros** [comment]
Thank you for the follow up. Makes perfect sense. thanks again.
